### ISSUE TITLE
Need Guidance on CORS workaround/solution

### ISSUE THREAD

**Issue by karla-moreno** [wdi-atx-12/class#2]
We are currently trying to get Yelp API information to display on the console to make sure it's working.

Things that work:
- get JSON response back using our access token in Postman.
- get JSON response back using access token in NPM's runkit using yelp-fusion package

What we get in console when we run it:
`Failed to load https://api.yelp.com/v3/businesses/search?term=ChiLantro&location=austin: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

What we want to return:
`Object {latitude: 30.252212, longitude: -97.763751}`

After extensive googling, it;s been suggested to turn off some chrome security measures to avoid that be we are concerned that it will only allow **us** to use it properly.

**Comment by jhnsnc** [comment]
ahh.. so Britney Jo and I had hoped this wouldn't be an issue. Basically, CORS is a browser thing where the browser will disallow requests coming from other domains unless their server explicitly allows it. Often, APIs will purposefully not allow these cross-origin requests since making a request to their API from a browser would inherently be exposing the developer's API key (which is a security risk).

So instead you'll have to "proxy" the requests. This means for each endpoint you want to use on the Yelp API, you'll create a matching endpoint on your own back-end server. Your front-end will make the request to your back-end server, your server will get the data from the Yelp API, and then your server will hand off the data to your front-end.

Depending on how you set up your project, you may need to set an `Access-Control-Allow-Origin` header in your proxy handlers. Other than that, your proxy is really just handing off the data from the API.
