### ISSUE TITLE
Cross server API call Error

### ISSUE THREAD

**Issue by CescoIV** [wdi-atx-12/class#3]
While trying to access the YelpAPI, i ran into the following error after an axios get request:

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.

I have my token key and all authentication going, I've  read that this is a CORS problem but I dont recall this being an issue with previous APIs we have visited nor am I sure of what cors of action to take next despite my searching, any help would be appreciated :)

**Comment by jhnsnc** [comment]
ahh.. so Britney Jo and I had hoped this wouldn't be an issue. Basically, CORS is a browser thing where the browser will disallow requests coming from other domains unless their server explicitly allows it. Often, APIs will purposefully not allow these cross-origin requests since making a request to their API from a browser would inherently be exposing the developer's API key (which is a security risk).

So instead you'll have to "proxy" the requests. This means for each endpoint you want to use on the Yelp API, you'll create a matching endpoint on your own back-end server. Your front-end will make the request to your back-end server, your server will get the data from the Yelp API, and then your server will hand off the data to your front-end.

Depending on how you set up your project, you may need to set an `Access-Control-Allow-Origin` header in your proxy handlers. Other than that, your proxy is really just handing off the data from the API.

**Comment by CescoIV** [comment]
We aren't using a back-end with our api, we are using firebase. So would it be better to look for an alternate API, to add a back-end, or is this something we can do with firebase?

**Comment by jhnsnc** [comment]
Apparently there is a way to handle this via Firebase. Karla is working through the same issue right now, so maybe the two of you can work together on it.

Until you get it all working, it would probably be a good idea to create an object with dummy data so that your teammates can continue working as if the data is already there.
